#!/bin/sh
zola build

# The following directories are excluded from the Zola build.
# We use symlinks to them from the public subdirectory.

# 1. Zola doesn't handle copying a directory with symlinks
#    (references to the stable/unstable versions)
ln -s ../reference public/reference
# 2. Copying many tarballs is expensive.
ln -s ../releases public/releases
